#!/bin/bash

case "$(uname)" in
"Darwin")
  echo "== Installing OSX config..."

  if ! which brew &> /dev/null; then
    echo -n "Installing homebrew..."
    echo "===== curl homebrew" >> install_log
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/installi)" >> install_log 2>&1
    echo "===== END curl homebrew" >> install_log
    echo "done."
  fi

  if ! which stow &> /dev/null; then
    echo -n "Installing stow..."
    echo "===== brew install gnu-stow" >> install_log
    brew install gnu-stow >> install_log 2>&1
    echo "===== END brew install gnu-stow" >> install_log
    echo "done."
  fi
;;

"Linux")
    # https://github.com/dylanaraps/neofetch/blob/master/neofetch
    distro="$(awk -F 'NAME=' '/^NAME=/ {printf $2}' /etc/*ease)"
    distro="${distro//\"}"

    case "$distro" in
    "Ubuntu")
      if ! which stow &> /dev/null; then
        echo -n "Installing stow..."
        echo "===== sudo apt-get install stow" >> install_log
        sudo apt-get install stow >> install_log 2>&1
        echo "===== END sudo apt-get install stow" >> install_log
        echo "done."
      fi

      if ! which ctags &> /dev/null; then
        echo -n "Installing ctags..."
        echo "===== sudo apt-get install exuberant-ctags" >> install_log
        sudo apt-get install exuberant-ctags >> install_log 2>&1
        echo "===== END sudo apt-get install exuberant-ctags" >> install_log
        echo "done."
      fi
    ;;

    *)
      echo "== No config installation provided for [$distro]."
      exit 1
    esac
esac

echo -n "Stowing ~/.files/meat..."
echo "===== stow meat" >> install_log
stow meat >> install_log 2>&1
echo "===== END stow meat" >> install_log
echo "done."

echo -n "Cloning purag/scripts to ~/scripts..."
echo "===== git clone purag/scripts.git" >> install_log
git clone https://github.com/purag/scripts.git ~/scripts >> install_log 2>&1
echo "===== END git clone purag/scripts.git" >> install_log
echo "done."

if [ ! -f "~/.vim/autoload/plug.vim" ]; then
  echo -n "Downloading vim-plug..."
  echo "===== curl vim-plug" >> install_log
  curl -fsvLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim >> install_log 2>&1
  echo "===== END curl vim-plug" >> install_log
  echo "done."
fi

echo -n "Installing vim plugins..."
vim +PlugInstall +qall
echo "done."

echo "== Done."
echo "== View logs in $(pwd)/install_log."
