#!/bin/bash

case "$(uname)" in
"Darwin")
  echo "== Installing OSX config..."

  if ! which brew &> /dev/null; then
    echo -n "Installing homebrew..."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    echo "done."
  fi

  if ! which stow &> /dev/null; then
    echo -n "Installing stow..."
    brew install gnu-stow
    echo "done."
  fi
;;

"Linux")
    distro="$(awk -F 'NAME=' '/^NAME=/ {printf $2}' /etc/*ease)"
    distro="${distro//\"}"

    case "$distro" in
    "Ubuntu")
      if ! which stow &> /dev/null; then
        echo -n "Installing stow..."
        sudo apt-get install stow
        echo "done."
      fi

      if ! which ctags &> /dev/null; then
        echo -n "Installing ctags..."
        sudo apt-get install ctags
        echo "done."
      fi
    ;;

    *)
      echo "== No Linux config installation provided."
      exit 1
    esac
esac

echo -n "Stowing ~/.files/meat..."
stow meat
echo "done."

echo -n "Cloning purag/scripts to ~/scripts..."
git clone https://github.com/purag/scripts.git ~/scripts &> /dev/null
echo "done."

if [ ! -f "~/.vim/autoload/plug.vim" ]; then
  echo -n "Downloading vim-plug..."
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim &> /dev/null
  echo "done."
fi

echo -n "Installing vim plugins..."
vim +PlugInstall +qall
echo "done."

echo "== Done."
