#!/bin/bash

add_path () {
  # https://superuser.com/a/39995
  if [ -d "$1" ] && [[ ":$PATH:" != *":$1"* ]]; then
    export PATH="$PATH:$1"
  fi
}

add_path ~/scripts
add_path ~/.p
add_path ~/datasci/anaconda2/bin
